# Generated by Django 4.2.3 on 2023-07-18 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('texto', models.TextField()),
                ('hora', models.TimeField()),
                ('ubic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.address')),
            ],
        ),
    ]
