# Generated by Django 4.2.10 on 2024-02-23 15:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrevistado',
            name='edad',
            field=models.TextField(validators=[django.core.validators.RegexValidator('^[0-9]+$', 'Ingrese un valor numérico válido.')]),
        ),
        migrations.AlterField(
            model_name='note',
            name='entrevista',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
        migrations.AlterField(
            model_name='note',
            name='ubic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.address'),
        ),
    ]
