# Generated by Django 4.2.3 on 2023-07-26 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='entrevistado',
            new_name='entrevista',
        ),
        migrations.CreateModel(
            name='Entrevistado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('apellido', models.TextField()),
                ('edad', models.TextField()),
                ('profesion', models.TextField()),
                ('fechaEntr', models.DateTimeField(blank=True)),
                ('notaAsoc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maps.note')),
            ],
        ),
    ]
