# Generated by Django 4.2.3 on 2023-07-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_rename_entrevistado_note_entrevista_entrevistado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrevistado',
            name='fechaEntr',
            field=models.DateField(blank=True),
        ),
    ]
