# Generated by Django 4.2.3 on 2023-08-07 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_alter_note_ubic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrevistado',
            name='fechaEntr',
        ),
        migrations.RemoveField(
            model_name='note',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='note',
            name='entrevistado',
        ),
        migrations.AddField(
            model_name='entrevistado',
            name='nota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entrevistados', to='maps.note'),
        ),
        migrations.AlterField(
            model_name='address',
            name='tipo',
            field=models.CharField(choices=[('Cultivo', 'Cultivo'), ('Terreno', 'Terreno'), ('Rio', 'Rio')], max_length=25, null=True),
        ),
    ]
