# Generated by Django 4.2.3 on 2023-07-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_alter_entrevistado_fechaentr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrevistado',
            name='fechaEntr',
            field=models.DateTimeField(blank=True),
        ),
    ]
