# Generated by Django 4.2.3 on 2023-07-18 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_address_notas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='ubic',
        ),
    ]
