# Generated by Django 4.2.3 on 2023-07-28 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_alter_entrevistado_fechaentr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrevistado',
            name='fechaEntr',
            field=models.DateField(blank=True),
        ),
    ]
