# Generated by Django 4.2.3 on 2023-07-18 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deu_HM', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
